<?php
require_once '../../../../config/db.php'; // Your database connection
require_once '../../includes/helpers.php'; // Include your helper functions
include("../../../../functions/role_functions.php");

$page_title = "Invoices";
$action = $_GET['action'] ?? 'list';

if ($action === 'list') {
    header('Location: ./');
}

if ($action === 'create') {
    header('Location: add');
}

if($action === 'details') {
    header('Location: invoice');
}

if ($action === 'edit') {
    header('Location: edit');
}

if ($action === 'delete') {
    $id = $_GET['id'] ?? null;
    if (!$id) exit("Invoice ID is required");

    // $invoice = $db->query("SELECT id FROM sales_invoices WHERE id = ?", [$id])->fetch_assoc();
    // if (!$invoice) exit("Invoice not found.");

    $delete_invoice_item = $db->query("DELETE FROM sales_invoice_items WHERE invoice_id = $id");
    if($delete_invoice_item) $delete_invoice = $db->query("DELETE FROM sales_invoices WHERE id = $id");
    if (!$delete_invoice) {
        exit("Error deleting invoice: " . $db->error);
    } else {
        $_SESSION['success'] = "Invoice deleted successfully.";
        // Log the deletion
        require_once '../../../../functions/log_functions.php';
        log_activity($user_id, $company_id, 'delete_invoice', "Deleted invoice #{$id}");
    
        redirect('./');
    }
}

if ($action === 'pdf') {
    $id = $_GET['id'] ?? null;
    if (!$id) exit('Invoice ID is required');

    // $invoice = $db->query("SELECT * FROM sales_invoices WHERE id = $id")->fetch_assoc();
    $invoice = $db->query("
    SELECT i.*, c.name AS customer_name, c.email AS customer_email, c.phone AS customer_phone, c.address AS customer_address,
            l.name AS lead_name, l.email AS lead_email, l.phone AS lead_phone, l.address AS lead_address,
            o.order_number, o.total_amount AS order_total, q.quote_number, q.total AS quote_total, q.tax AS quote_tax,
            qc.name AS quote_cname, qc.email AS quote_cemail, qc.phone AS quote_cphone,
            oc.name AS order_cname, oc.email AS order_cemail, oc.phone AS order_cphone,
            ql.name AS quote_lname, ql.email AS quote_lemail, ql.phone AS quote_lphone
    FROM sales_invoices i
    LEFT JOIN sales_quotations q ON i.quotation_id = q.id
    LEFT JOIN sales_customers c ON i.customer_id = c.id
    LEFT JOIN sales_customers l ON i.lead_id = l.id
    LEFT JOIN sales_orders o ON i.order_id = o.id
    LEFT JOIN sales_customers qc ON q.customer_id = qc.id
    LEFT JOIN sales_customers oc ON o.customer_id = oc.id
    LEFT JOIN sales_customers ql ON q.lead_id = ql.id
    WHERE i.id = $id AND i.company_id = $company_id")->fetch_assoc();
    
    // Payments
    $payments = $db->query("SELECT * FROM sales_invoice_payments WHERE invoice_id = $id");
    // Logo
    $logo = $conn->query("SELECT logo FROM companies WHERE id = $company_id")->fetch_assoc()['logo'];
    // Customer
    $customer_name = $invoice['customer_name'] ?? $invoice['lead_name'] ?? $invoice['order_cname'] ?? $invoice['quote_cname'] ?? $invoice['quote_lname'];
    $customer_email = $invoice['customer_email'] ?? $invoice['lead_email'] ?? $invoice['order_cemail'] ?? $invoice['quote_cemail'] ?? $invoice['quote_lemail'];
    $customer_phone = $invoice['customer_phone'] ?? $invoice['lead_phone'] ?? $invoice['order_cphone'] ?? $invoice['quote_cphone'] ?? $invoice['quote_lphone'];

    require_once '../../../../vendor/tecnickcom/tcpdf/tcpdf.php';

    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('AIMIS Sales');
    $pdf->SetTitle('Invoice ' . $invoice['invoice_number']);
    $pdf->SetMargins(15, 20, 15);
    $pdf->AddPage();

    if(!empty($logo)) {
        $logoPath = "../../../../uploads/company/{$logo}";
        if (file_exists($logoPath)) {
            // $pdf->Image($logoPath, 15, $pdf->GetY(), 40);
            $pdf->Image($logoPath, 15, 15, 25);
            $pdf->Ln(20);
        }
    }

    // HTML content
    $html = "
      <h1>Invoice: {$invoice['invoice_number']}</h1>
      <p>
        <strong>Date:</strong> {$invoice['invoice_date']}<br>
        <strong>Due:</strong> {$invoice['due_date']}<br>
        <strong>Status:</strong> {$invoice['status']}
      </p>

      <h3>Bill To:</h3>
      <p>
        {$customer_name}<br>
        {$customer_email}<br>
        {$customer_phone}<br>
      </p>

      <h3>Invoice Summary:</h3>
      <table border='1' cellpadding='5'>
        <tr><th>Description</th><th>Amount</th></tr>
        <tr><td>Total</td><td>N" . number_format($invoice['total_amount'], 2) . "</td></tr>
        <tr><td>Paid</td><td>N" . number_format($invoice['payment_received'], 2) . "</td></tr>
        <tr><td><strong>Balance</strong></td><td><strong>N" . number_format($invoice['total_amount'] - $invoice['payment_received'], 2) . "</strong></td></tr>
      </table>

      <br><br>
      <p><em>Generated by AIMIS System</em></p>
    ";

    $pdf->writeHTML($html, true, false, true, false, '');

    // Add Signature
    // ... previous $pdf->writeHTML($html)

    $pdf->Ln(10); // Add space before signature

    $signatureHTML = "
    <p><strong>Digitally Signed</strong></p>
    <p>Signed by: AIMIS Signature Authority<br>
    Signed on: " . date('Y-m-d H:i:s') . "</p>
    ";

    // Add signature image if available
    // $signaturePath = "/public/assets/img/signature.png";
    // if (file_exists($signaturePath)) {
    //     $pdf->Image($signaturePath, 15, $pdf->GetY(), 40);
    //     $pdf->Ln(20);
    // }

    $pdf->writeHTML($signatureHTML, true, false, true, false, '');

    $pdf->Output("Invoice_{$invoice['invoice_number']}.pdf", 'I'); // Output to browser
    exit;
}

if ($action === 'send_for_signature') {
    $id = $_GET['id'] ?? null;
    if (!$id) exit('Invoice ID required');

    $invoice = $db->query("SELECT * FROM sales_invoices WHERE id = $id")->fetch_assoc();
    $customer = $db->query("SELECT * FROM sales_customers WHERE id = {$invoice['customer_id']}")->fetch_assoc();

    // Generate PDF to temp file
    require_once '../../../../vendor/tecnickcom/tcpdf/tcpdf.php';
    $pdf = new TCPDF();
    $pdf->AddPage();
    $pdf->writeHTML("<h1>Invoice {$invoice['invoice_number']}</h1>");
    $tempPdfPath = sys_get_temp_dir() . "/invoice_{$id}.pdf";
    $pdf->Output($tempPdfPath, 'F');

    // Prepare webhook payload
    $webhookUrl = 'https://third-party-sign.example.com/api/sign';
    $callbackUrl = './webhook/signature_callback.php';

    $post = [
        'invoice_id' => $id,
        'customer_email' => $customer['email'],
        'callback_url' => $callbackUrl
    ];

    $file = curl_file_create($tempPdfPath, 'application/pdf', basename($tempPdfPath));
    $post['file'] = $file;

    $ch = curl_init($webhookUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    $status = ($httpCode === 200) ? 'pending' : 'failed';
    $db->insert('sales_invoice_signatures', [
        'invoice_id' => $id,
        'status' => $status,
        'webhook_response' => $response,
        'requested_at' => date('Y-m-d H:i:s')
    ]);

    unlink($tempPdfPath); // Cleanup
    redirect("invoice?id=$id");
}




