<?php
require_once '../../../../config/db.php'; // Your database connection
require_once '../../includes/helpers.php'; // Include your helper functions

$page_title = "Invoices";
$action = $_GET['action'] ?? 'list';

if ($action === 'list') {
    header('Location: list.php');
}

if ($action === 'create') {
    header('Location: create.php');
}

if($action === 'details') {
    header('Location: details.php');
}

if ($action === 'edit') {
    header('Location: edit.php');
}

if ($action === 'delete') {
    $id = $_GET['id'] ?? null;
    if (!$id) exit("Invoice ID is required");

    $invoice = $db->query("SELECT id FROM sales_invoices WHERE id = ?", [$id])->fetch_assoc();
    if (!$invoice) exit("Invoice not found.");

    $delete = $db->query("DELETE FROM sales_invoices WHERE id = $id");
    if (!$delete) {
        exit("Error deleting invoice: " . $db->error);
    } else {
        $_SESSION['success'] = "Invoice deleted successfully.";
        // Log the deletion
        require_once '../../../../functions/log_functions.php';
        log_activity($_SESSION['user_id'], $_SESSION['company_id'], 'delete_invoice', "Deleted invoice #{$id}");
    
        redirect('invoices.php');
    }
}

if ($action === 'pdf') {
    $id = $_GET['id'] ?? null;
    if (!$id) exit('Invoice ID is required');

    $invoice = $db->fetch("SELECT * FROM sales_invoices WHERE id = ?", [$id]);
    $customer = $db->fetch("SELECT * FROM sales_customers WHERE id = ?", [$invoice['customer_id']]);
    $payments = $db->fetchAll("SELECT * FROM sales_invoice_payments WHERE invoice_id = ?", [$id]);

    require_once BASE_PATH . '/vendor/tcpdf/tcpdf.php';

    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('AIMIS Sales');
    $pdf->SetTitle('Invoice ' . $invoice['invoice_number']);
    $pdf->SetMargins(15, 20, 15);
    $pdf->AddPage();

    // HTML content
    $html = "
      <h1>Invoice: {$invoice['invoice_number']}</h1>
      <p><strong>Date:</strong> {$invoice['invoice_date']}<br>
         <strong>Due:</strong> {$invoice['due_date']}<br>
         <strong>Status:</strong> {$invoice['status']}</p>

      <h3>Bill To:</h3>
      <p>
        {$customer['company_name']}<br>
        {$customer['email']}<br>
        {$customer['phone']}<br>
      </p>

      <h3>Invoice Summary:</h3>
      <table border='1' cellpadding='5'>
        <tr><th>Description</th><th>Amount</th></tr>
        <tr><td>Total</td><td>$" . number_format($invoice['total_amount'], 2) . "</td></tr>
        <tr><td>Paid</td><td>$" . number_format($invoice['payment_received'], 2) . "</td></tr>
        <tr><td><strong>Balance</strong></td><td><strong>$" . number_format($invoice['total_amount'] - $invoice['payment_received'], 2) . "</strong></td></tr>
      </table>

      <br><br>
      <p><em>Generated by AIMIS System</em></p>
    ";

    $pdf->writeHTML($html, true, false, true, false, '');

    // Add Signature
    // ... previous $pdf->writeHTML($html)

    $pdf->Ln(10); // Add space before signature

    $signatureHTML = "
    <p><strong>Digitally Signed</strong></p>
    <p>Signed by: AIMIS Signature Authority<br>
    Signed on: " . date('Y-m-d H:i:s') . "</p>
    ";

    // Add signature image if available
    $signaturePath = BASE_PATH . "/public/assets/img/signature.png";
    if (file_exists($signaturePath)) {
        $pdf->Image($signaturePath, 15, $pdf->GetY(), 40);
        $pdf->Ln(20);
    }

    $pdf->writeHTML($signatureHTML, true, false, true, false, '');

    $pdf->Output("Invoice_{$invoice['invoice_number']}.pdf", 'I'); // Output to browser
    exit;
}

if ($action === 'send_for_signature') {
    $id = $_GET['id'] ?? null;
    if (!$id) exit('Invoice ID required');

    $invoice = $db->fetch("SELECT * FROM sales_invoices WHERE id = ?", [$id]);
    $customer = $db->fetch("SELECT * FROM sales_customers WHERE id = ?", [$invoice['customer_id']]);

    // Generate PDF to temp file
    require_once BASE_PATH . '/vendor/tcpdf/tcpdf.php';
    $pdf = new TCPDF();
    $pdf->AddPage();
    $pdf->writeHTML("<h1>Invoice {$invoice['invoice_number']}</h1>");
    $tempPdfPath = sys_get_temp_dir() . "/invoice_{$id}.pdf";
    $pdf->Output($tempPdfPath, 'F');

    // Prepare webhook payload
    $webhookUrl = 'https://third-party-sign.example.com/api/sign';
    $callbackUrl = BASE_URL . '/webhook/signature_callback.php';

    $post = [
        'invoice_id' => $id,
        'customer_email' => $customer['email'],
        'callback_url' => $callbackUrl
    ];

    $file = curl_file_create($tempPdfPath, 'application/pdf', basename($tempPdfPath));
    $post['file'] = $file;

    $ch = curl_init($webhookUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    $status = ($httpCode === 200) ? 'pending' : 'failed';
    $db->insert('sales_invoice_signatures', [
        'invoice_id' => $id,
        'status' => $status,
        'webhook_response' => $response,
        'requested_at' => date('Y-m-d H:i:s')
    ]);

    unlink($tempPdfPath); // Cleanup
    redirect("invoices.php?action=details&id=$id");
}




