<footer class="app-footer">
    <!--begin::To the end-->
    <div class="float-end d-none d-sm-inline">
        <a href="https://itplace.com.ng" target="_blank">ITPlace Nigeria</a>
    </div>
    <!--end::To the end-->
    <!--begin::Copyright-->
    <strong>
        Copyright &copy; 2025&nbsp;
        <a href="#" class="text-decoration-none">AIMIS Cloud</a>.
    </strong>
    All rights reserved.
    <!--end::Copyright-->
</footer>