<!-- AI Chat Window -->
<!-- <div class="chat-popup" id="aiChatAssistant">
  <form action="/action_page.php" class="form-container card">
    <div class="card-header">
        <h3 class="card-title">AI Assistant</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-danger btn-sm" onclick="closeForm()">X</button>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            <img src="/w3images/bandmember.jpg" alt="Avatar">
            <p>Hello. How are you today?</p>
            <span class="time-right">11:00</span>
        </div>

        <div class="container darker">
            <img src="/w3images/avatar_g2.jpg" alt="Avatar" class="right">
            <p>Hey! I'm fine. Thanks for asking!</p>
            <span class="time-left">11:01</span>
        </div>

        <div class="container">
            <img src="/w3images/bandmember.jpg" alt="Avatar">
            <p>Sweet! So, what do you wanna do today?</p>
            <span class="time-right">11:02</span>
        </div>

        <div class="container darker">
            <img src="/w3images/avatar_g2.jpg" alt="Avatar" class="right">
            <p>Nah, I dunno. Play soccer.. or learn more coding perhaps?</p>
            <span class="time-left">11:05</span>
        </div>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <input type="text" name="msg" class="form-control">
                </div>
            </div>
            <div class="col-auto">
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Send</button>
                </div>
            </div>
        </div>
    </div>
  </form>
</div> -->

<!-- <div class="chat-popup" id="aiChatAssistant">
  <form action="/action_page.php" class="form-container">
    <h1>Chat</h1>

    <label for="msg"><b>Message</b></label>
    <textarea placeholder="Type message.." name="msg" required></textarea>

    <button type="submit" class="btn">Send</button>
    <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
  </form>
</div> -->
<!-- /. AI Chat Window -->
<footer class="app-footer">
    <!--begin::To the end-->
    <div class="float-end d-none d-sm-inline">
        <a href="https://itplace.com.ng" target="_blank">ITPlace Nigeria</a>
    </div>
    <!-- <div class="float-end">
        <button class="open-button" onclick="openForm()">Chat</button>
    </div> -->
    <!--end::To the end-->
    <!--begin::Copyright-->
    <strong>
        Copyright &copy; 2025&nbsp;
        <a href="#" class="text-decoration-none">AIMIS Cloud</a>.
    </strong>
    All rights reserved.
    <!--end::Copyright-->
</footer>