<nav class="app-header navbar navbar-expand bg-body">
    <!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Start Navbar Links-->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button">
                <i class="bi bi-list"></i>
                </a>
            </li>
        </ul>
        <!--end::Start Navbar Links-->

        <!--begin::End Navbar Links-->
        <ul class="navbar-nav ms-auto">
            <!--begin::Messages Dropdown Menu-->
            
            <!--end::Messages Dropdown Menu-->

            <!--begin::Notifications Dropdown Menu-->
            
            <!--end::Notifications Dropdown Menu-->

            <!--begin::Fullscreen Toggle-->
            <li class="nav-item">
                <a class="nav-link" href="#" data-lte-toggle="fullscreen">
                    <i data-lte-icon="maximize" class="bi bi-arrows-fullscreen"></i>
                    <i data-lte-icon="minimize" class="bi bi-fullscreen-exit" style="display: none"></i>
                </a>
            </li>
            <!--end::Fullscreen Toggle-->

            <!--begin::User Menu Dropdown-->
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    <img src="/uploads/users/<?php echo $_SESSION['user_avatar']; ?>" class="user-image rounded-circle shadow" alt="User Image"/>
                    <span class="d-none d-md-inline"><?php echo $_SESSION['user_name']; ?></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end">
                    <!--begin::User Image-->
                    <li class="user-header text-bg-primary">
                        <img src="/uploads/users/<?php echo $_SESSION['user_avatar']; ?>" class="rounded-circle shadow" alt="User Image"/>
                        <!-- <p>
                            <?php //echo $_SESSION['user_name']; ?> - <?php //echo $_SESSION['user_department']; ?>
                            <small><?php //echo $_SESSION['user_role']; ?></small>
                        </p> -->
                        <p>
                            <?php echo $_SESSION['user_name']; ?>
                            <small><?php echo ucfirst($_SESSION['user_role']); ?></small>
                        </p>
                    </li>
                    <!--end::User Image-->

                    <!--begin::Menu Footer-->
                    <li class="user-footer">
                        <?php if($_SESSION['employee_id'] != '' && $_SESSION['employee_id'] !== 0 && !empty($_SESSION['employee_id'])) { ?>
                            <a href="/payroll/employees/employee" class="btn btn-default btn-flat">My Profile</a>
                        <?php } else { ?>
                            <a href="/modules/settings/profile" class="btn btn-default btn-flat">My Profile</a>
                        <?php } ?>
                        <a href="/logout" class="btn btn-default btn-flat float-end">Log Out</a>
                    </li>
                    <!--end::Menu Footer-->
                </ul>
            </li>
            <!--end::User Menu Dropdown-->
        </ul>
        <!--end::End Navbar Links-->
    </div>
    <!--end::Container-->
</nav>